"""Shared pytest fixtures for qemsel tests.

These fixtures are OWNED BY THE ARCHITECT skeleton — builders add their own
test files under tests/ (test_<module>.py) but do not edit this file.

Design goal: module tests must never need heavy noisy simulation. The
``fake_executor`` fixture satisfies the exact ``backends.make_executor``
executor contract using an exact statevector (fast, deterministic,
noiseless), so mitigation/experiment logic can be tested without Aer noise
models.
"""

from __future__ import annotations

from pathlib import Path
from typing import Callable

import numpy as np
import pandas as pd
import pytest
from qiskit import QuantumCircuit

# Techniques / feature names duplicated here as literals on purpose: conftest
# must import even while builder modules are still stubs.
_TECHNIQUES = ["raw", "zne", "cdr", "rem"]
_FEATURE_NAMES = [
    "n_qubits",
    "depth",
    "n_1q_gates",
    "n_2q_gates",
    "n_cnot",
    "n_non_clifford",
    "clifford_fraction",
    "depth_per_qubit",
    "backend_avg_2q_error",
    "backend_avg_readout_error",
]


@pytest.fixture()
def tiny_circuit() -> QuantumCircuit:
    """Deterministic 2-qubit Bell-pair circuit WITHOUT measurements.

    Ideal expectations: <ZZ> = +1.0, <ZI> = <IZ> = 0.0, <XX> = +1.0.
    """
    qc = QuantumCircuit(2)
    qc.h(0)
    qc.cx(0, 1)
    return qc


@pytest.fixture()
def tiny_identity_circuit() -> QuantumCircuit:
    """3-qubit circuit logically equal to identity (mirror-style).

    Ideal expectation of 'ZZZ' is exactly +1.0 — handy for mitigation tests.
    """
    qc = QuantumCircuit(3)
    qc.h(0)
    qc.cx(0, 1)
    qc.cx(1, 2)
    qc.cx(1, 2)
    qc.cx(0, 1)
    qc.h(0)
    return qc


@pytest.fixture()
def fake_executor() -> Callable[[QuantumCircuit, str], float]:
    """Noiseless executor satisfying the make_executor contract exactly.

    executor(circuit, pauli) -> float, where pauli follows the qemsel
    convention: pauli[i] acts on qubit i (REVERSED vs qiskit Pauli labels).
    Exact statevector — no shots, no noise, fully deterministic.
    """
    from qiskit.quantum_info import Pauli, Statevector

    def _exec(circuit: QuantumCircuit, pauli: str) -> float:
        if len(pauli) != circuit.num_qubits:
            raise ValueError(
                f"pauli length {len(pauli)} != num_qubits {circuit.num_qubits}"
            )
        if any(c not in "IXYZ" for c in pauli):
            raise ValueError(f"invalid pauli string: {pauli!r}")
        sv = Statevector.from_instruction(circuit)
        # qemsel convention -> qiskit label convention: reverse the string.
        return float(np.real(sv.expectation_value(Pauli(pauli[::-1]))))

    return _exec


@pytest.fixture()
def out_dir(tmp_path: Path) -> Path:
    """Fresh empty output directory (pathlib.Path) inside pytest's tmp tree."""
    d = tmp_path / "out"
    d.mkdir(parents=True, exist_ok=True)
    return d


@pytest.fixture()
def tiny_results_df() -> pd.DataFrame:
    """Synthetic results DataFrame matching the EXACT run_experiment row schema.

    16 rows, 4 rows per class ('raw','zne','cdr','rem' as best_technique), so
    stratified CV with up to 4 splits works. Lets model/report tests run
    without any quantum simulation.
    """
    rng = np.random.default_rng(42)
    rows = []
    families = ["layered_random", "near_clifford", "ghz_plus", "mirror_circuit"]
    backends = ["FakeManilaV2", "FakeLagosV2"]
    for i in range(16):
        best = _TECHNIQUES[i % 4]
        family = families[i % 4]
        n_qubits = 2 + (i % 3)
        depth = 4 * (1 + i % 4)
        seed = i
        backend = backends[i % 2]
        ideal = 1.0 if family == "mirror_circuit" else float(rng.uniform(-1, 1))
        feats = {
            "feat_n_qubits": float(n_qubits),
            "feat_depth": float(depth),
            "feat_n_1q_gates": float(n_qubits * depth),
            "feat_n_2q_gates": float((n_qubits - 1) * depth // 2),
            "feat_n_cnot": float((n_qubits - 1) * depth // 2),
            "feat_n_non_clifford": float(i % 5),
            "feat_clifford_fraction": float(rng.uniform(0.5, 1.0)),
            "feat_depth_per_qubit": float(depth / n_qubits),
            "feat_backend_avg_2q_error": 0.01 if backend == "FakeManilaV2" else 0.02,
            "feat_backend_avg_readout_error": (
                0.03 if backend == "FakeManilaV2" else 0.15
            ),
        }
        assert list(feats) == ["feat_" + n for n in _FEATURE_NAMES]
        row = {
            "circuit_id": f"{family}_q{n_qubits}_d{depth}_s{seed}",
            "family": family,
            "n_qubits": n_qubits,
            "depth": depth,
            "seed": seed,
            "backend": backend,
            "pauli": "Z" * n_qubits,
            "ideal": ideal,
            **feats,
        }
        # Give the designated best technique the smallest abs error.
        for tech in _TECHNIQUES:
            err = 0.01 if tech == best else float(rng.uniform(0.05, 0.3))
            mult = {"raw": 1, "zne": 3, "cdr": 11, "rem": 3}[tech]
            row[f"{tech}_value"] = ideal + err
            row[f"{tech}_abs_error"] = err
            row[f"{tech}_shots"] = 1024 * mult
        row["best_technique"] = best
        rows.append(row)
    return pd.DataFrame(rows)
